
package stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.Holder;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProductsManager", targetNamespace = "http://webservices.amoa/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductsManager {


    /**
     * 
     * @param product
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "productId", partName = "productId")
    @Action(input = "http://webservices.amoa/ProductsManager/addProductRequest", output = "http://webservices.amoa/ProductsManager/addProductResponse")
    public int addProduct(
        @WebParam(name = "product", partName = "product")
        Product product);

    /**
     * 
     * @param productId
     * @return
     *     returns stub.Product
     * @throws NoSuchProductException_Exception
     */
    @WebMethod
    @WebResult(name = "product", partName = "product")
    @Action(input = "http://webservices.amoa/ProductsManager/getProductRequest", output = "http://webservices.amoa/ProductsManager/getProductResponse", fault = {
        @FaultAction(className = NoSuchProductException_Exception.class, value = "http://webservices.amoa/ProductsManager/getProduct/Fault/NoSuchProductException")
    })
    public Product getProduct(
        @WebParam(name = "productId", partName = "productId")
        int productId)
        throws NoSuchProductException_Exception
    ;

    /**
     * 
     * @param product
     */
    @WebMethod
    @Action(input = "http://webservices.amoa/ProductsManager/updateProductRequest", output = "http://webservices.amoa/ProductsManager/updateProductResponse")
    public void updateProduct(
        @WebParam(name = "product", mode = WebParam.Mode.INOUT, partName = "product")
        Holder<Product> product);

    /**
     * 
     * @param productId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.amoa/ProductsManager/deleteProductRequest", output = "http://webservices.amoa/ProductsManager/deleteProductResponse")
    public boolean deleteProduct(
        @WebParam(name = "productId", partName = "productId")
        int productId);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices.amoa/ProductsManager/deleteAllProductsRequest", output = "http://webservices.amoa/ProductsManager/deleteAllProductsResponse")
    public boolean deleteAllProducts();

    /**
     * 
     * @return
     *     returns stub.Products
     */
    @WebMethod
    @WebResult(name = "products", partName = "products")
    @Action(input = "http://webservices.amoa/ProductsManager/getProductsRequest", output = "http://webservices.amoa/ProductsManager/getProductsResponse")
    public Products getProducts();

    /**
     * 
     * @param productId
     * @return
     *     returns double
     * @throws NoSuchProductException_Exception
     */
    @WebMethod
    @WebResult(name = "price", partName = "price")
    @Action(input = "http://webservices.amoa/ProductsManager/getProductPriceRequest", output = "http://webservices.amoa/ProductsManager/getProductPriceResponse", fault = {
        @FaultAction(className = NoSuchProductException_Exception.class, value = "http://webservices.amoa/ProductsManager/getProductPrice/Fault/NoSuchProductException")
    })
    public double getProductPrice(
        @WebParam(name = "productId", partName = "productId")
        int productId)
        throws NoSuchProductException_Exception
    ;

}
